In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\datasets\\customer.csv")
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

Train Test splitting

In [25]:
x=df[['gender']] #dataframe (2D)
y=df['purchased'] #dataframe (1D)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
type(x_train)

pandas.DataFrame

Applying One Hot Encoding on input column

In [ ]:
ohe=OneHotEncoder()
x_train_new=ohe.fit_transform(x_train[["gender"]]).toarray()
x_train_new

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [32]:
x_test_new=ohe.transform(x_test[["gender"]]).toarray()
x_test_new

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

Applying Label Encoding on output column

In [33]:
le=LabelEncoder()
le.fit(y_train)
y_train_new=le.transform(y_train)
y_train_new

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [34]:
y_test_new=le.transform(y_test)
y_test_new

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])